# 
# @file dgm_parameters_bolt.yaml
# @author Elham Daneshmand (exledh@gmail.com)
# @license License BSD-3-Clause
# @copyright Copyright (c) 2019, New York University and Max Planck Gesellschaft.
# 
# @brief Define the interface between the control and the hardware
# 

is_real_robot: true
device:
  name: "bolt"
  sensors:
    # joints data
    joint_positions:
      size: 6
    joint_velocities:
      size: 6
    joint_torques:
      size: 6
    joint_target_torques:
      size: 6
    joint_encoder_index:
      size: 6
    # additional data
    slider_positions:
      size: 4
    # robot status
    motor_enabled:
      size: 6
    motor_ready:
      size: 6
    motor_board_enabled:
      size: 3
    motor_board_errors:
      size: 3
  controls:
    ctrl_joint_torques:
      size: 6
hardware_communication:
  max_missed_control: 10
  control_period: 1000000 # in nano second this means 1ms <=> 1kz
  maximum_time_for_user_cmd: 100000
  # Angle between the next index and the home position(joint_positions=12*[0.,])
  calibration:
    # 'FL_HAA', 'FL_HFE', 'FL_KFE', 'FR_HAA', 'FR_HFE', 'FR_KFE'
    index_to_zero_angle: [-0.103810, -0.418661, -0.139920, -0.472622, -0.204885, -0.609037, ]
  network_id: "ens4"

motor_I: 0.045     # The inertia of a single blmc_motor
motor_KT: 0.025    # The Kt constant of the motor [Nm/A]: tau = I * Kt
motor_gear_ratio: 9 # On the quadruped the gear ration is 1:9
